# Generated by Django 3.1.4 on 2021-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['act', 'chapter', 'number']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['act', 'number']},
        ),
        migrations.AddField(
            model_name='act',
            name='source_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='regulations',
            name='source_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
