# Generated by Django 3.1.4 on 2021-03-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_auto_20210225_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
