# Generated by Django 3.1.4 on 2021-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_auto_20210327_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='termination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
